version: "3.9"
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1GB
    networks:
      - net
  thesis-backend:
    image: thesis-backend
    container_name: thesis-backend
    restart: unless-stopped
    ports:
      - 80:3000
    deploy:
      resources:
        limits:
          memory: 1GB
    depends_on:
      - mongodb
    networks:
      - net
volumes:
   mongodb_data:
     driver: local
networks:
  net:
    driver: bridge